<?php

$a[] = "Breast Cancer";
$a[] = "Colorectal Cancer";
$a[] = "Lung Cancer";
$a[] = "Cervical Vancer";
$a[] = "Thyroid_Cancer";
$q = $_REQUEST["q"];
$hint = "";
switch($q)
{
	case 'Breast Cancer':
	echo "Whether you or a loved one are worried about developing breast cancer, have just been diagnosed, are going through breast cancer treatment, or are trying to stay well after treatment, this detailed information can help you find the answers you need.~Breast cancer is a type of cancer that starts in the breast. Cancer starts when cells begin to grow out of control.Breast cancer occurs almost entirely in women, but men can get breast cancer, too.Breast cancer cells usually form a tumor that can often be seen on an x-ray or felt as a lump.  ~There are several Lifestyle-related Breast Cancer Risk Factors as - drinking alcohol, being overweight or obese, not being physically active, birth control etc. For its prevention ,we may go through the facts as -Genetic Counseling and Testing for Breast Cancer Risk, Deciding Whether to Use Medicine to Reduce Breast Cancer Risk, Preventive Surgery to Reduce Breast Cancer Risk etc.~Breast cancer is sometimes found after symptoms appear, but many women with breast cancer have no symptoms. This is why regular breast cancer screening is so important. Different tests can be used to look for and diagnose breast cancer. If your doctor finds an area of concern on a screening test (a mammogram), or if you have symptoms that could mean breast cancer, you will need more tests to know for sure if it’s cancer.~There are several types of breast cancer. The type of breast cancer you have depends on where in the breast it started and other factors. If you have been diagnosed with breast cancer, tests will be done to find out the extent (stage) of the cancer. The stage of a cancer helps determine how serious the cancer is and how best to treat it.~Some treatments are local, meaning they treat the tumor without affecting the rest of the body. Most women with breast cancer will have some type of surgery to remove the tumor. Depending on the type of breast cancer and how advanced it is, you might need other types of treatment as well, either before or after surgery, or sometimes both.";
	case 'Lung Cancer':
	echo "Whether you or a loved one are worried about developing lung cancer, have just been diagnosed, are going through lung cancer treatment, or are trying to stay well after treatment, this detailed information can help you find the answers you need.~Lung cancer is a type of cancer that starts in the lungs. Cancer starts when cells in the body begin to grow out of control.When you breathe in, air enters through your mouth or nose and goes into your lungs through the trachea (windpipe). The trachea divides into tubes called bronchi, which enter the lungs and divide into smaller bronchi. These divide to form smaller branches called bronchioles. At the end of the bronchioles are tiny air sacs known as alveoli.The alveoli absorb oxygen into your blood from the inhaled air and remove carbon dioxide from the blood when you exhale. Taking in oxygen and getting rid of carbon dioxide are your lungs’ main functions.Lung cancers typically start in the cells lining the bronchi and parts of the lung such as the bronchioles or alveoli.~Several risk factors can make you more likely to develop lung cancer.  These factors are related to the risk of lung cancer in general.Risk factors you can change -Tobacco smoke, Secondhand smoke, Taking certain dietary supplements, Arsenic in drinking water etc.Risk factors you cannot change-Previous radiation therapy to the lungs, Air pollution, Personal or family history of lung cancer etc.There are things you can do that might lower your risk, such as changing the risk factors that you can control - Stay away from tobacco, Avoid or limit exposure to cancer-causing agents, Eat a healthy diet etc.~The most common symptoms of lung cancer are: A cough that does not go away or gets worse, Coughing up blood or rust-colored sputum (spit or phlegm), Chest pain that is often worse with deep breathing, coughing, or laughing, Hoarseness, Loss of appetite, Unexplained weight loss. Shortness of breath, Feeling tired or weak etc~Some lung cancers can be found by screening, but most lung cancers are found because they are causing problems. The actual diagnosis of lung cancer is made by looking at a sample of lung cells in the lab. you can go through - Medical history and physical exam, Imaging tests to look for lung cancer, Chest x-ray, Computed tomography (CT) scan etc~Surgery for Non-Small Cell Lung Cancer, Radiofrequency Ablation (RFA) for Non-Small Cell Lung Cancer, Radiation Therapy for Non-Small Cell Lung Cancer, Chemotherapy for Non-Small Cell Lung Cancer, Targeted Therapy for Non-Small Cell Lung Cancer,Immunotherapy for Non-Small Cell Lung Cancer,Palliative Procedures for Non-Small Cell Lung Cancer.Treatments for SCLC can include:Chemotherapy for Small Cell Lung Cancer,Immunotherapy for Small Cell Lung Cancer,Radiation Therapy for Small Cell Lung Cancer,Surgery for Small Cell Lung Cancer.Palliative Procedures for Small Cell Lung Cancer.";
	case $a[2]:
	echo "";
	case $a[3]:
	echo "";
	case $a[4]:
	echo "";
	case $a[5]:
	echo "";
}
?>